In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.width', 1000)

def answer_one():
    energy = pd.read_excel("./Energy Indicators.xls", skiprows=18, skipfooter=38, header=None)
    energy = energy.drop(energy.columns[[0, 1]], axis=1)
    energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
    energy = energy.replace("...", np.nan)
    energy['Energy Supply'] = energy['Energy Supply'] * 1000000
    energy['Country'] = energy['Country'].str.replace(r'\d+', '', regex=True)
    energy['Country'] = energy['Country'].str.replace(r'\(.*\)', '' ,regex=True).str.strip()
    energy['Country'] = energy['Country'].replace({
        'Republic of Korea': 'South Korea', 
        'United States of America': 'United States',
        'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
        'China, Hong Kong Special Administrative Region': 'Hong Kong'
    })

    GDP = pd.read_csv("./world_bank.csv",skiprows=4)
    GDP['Country Name'] = GDP['Country Name'].replace({
        'Korea, Rep.': 'South Korea',
        'Iran, Islamic Rep.': 'Iran',
        'Hong Kong SAR, China': 'Hong Kong'
    })

    ScimEn = pd.read_excel("./ScimEn.xlsx")
    ScimEn = ScimEn[ScimEn['Rank'] <= 15]
    
    together = pd.merge(ScimEn, energy, how='inner', on='Country')
    together = pd.merge(together, GDP, how='inner', left_on='Country', right_on='Country Name')
    together = together.set_index('Country')

    together = together[['Rank', 'Documents', 'Citable documents', 'Citations', 
                     'Self-citations', 'Citations per document', 'H index',
                     'Energy Supply', 'Energy Supply per Capita', '% Renewable',
                     '2006', '2007', '2008', '2009', '2010', '2011', '2012', 
                     '2013', '2014', '2015']]
    return together


answer_one()

                    Rank  Documents  Citable documents  Citations  Self-citations  Citations per document  H index Energy Supply Energy Supply per Capita  % Renewable          2006          2007          2008          2009          2010          2011          2012          2013          2014          2015
Country
China                  1     472465             470142    6591474         4594673                   13.95      380  127191000000                       93    19.754910  2.791498e+12  3.604056e+12  4.667346e+12  5.189577e+12  6.192565e+12  7.671757e+12  8.673665e+12  9.743124e+12  1.067453e+13  1.128081e+13
United States          2     222772             217929    4131736         1119917                   18.55      491   90838000000                      286    11.570980  1.381559e+13  1.447423e+13  1.476986e+13  1.447806e+13  1.504896e+13  1.559973e+13  1.625397e+13  1.684319e+13  1.755068e+13  1.820602e+13
India                  3      96975              94714    1243636          479638                   12.82      258   33195000000                       26    14.969080  9.402599e+11  1.216736e+12  1.198895e+12  1.341888e+12  1.675616e+12  1.823052e+12  1.827638e+12  1.856722e+12  2.039126e+12  2.103588e+12
United Kingdom         4      61946              60287    1326766          207337                   21.42      313    7920000000                      124    10.600470  2.719558e+12  3.104700e+12  2.945252e+12  2.429358e+12  2.496741e+12  2.675590e+12  2.719716e+12  2.796908e+12  3.085362e+12  2.945580e+12
Japan                  5      61939              61307     813472          166907                   13.13      246   18984000000                      149    10.232820  4.601663e+12  4.579751e+12  5.106679e+12  5.289493e+12  5.759072e+12  6.233147e+12  6.272363e+12  5.212328e+12  4.896994e+12  4.444931e+12
Germany                6      55466              54296     932195          185376                   16.81      274   13261000000                      165    17.901530  3.046309e+12  3.484057e+12  3.808198e+12  3.478546e+12  3.467094e+12  3.823576e+12  3.596483e+12  3.807024e+12  3.964871e+12  3.425100e+12
Russian Federation     7      49938              49562     268391          112125                    5.37      123   30709000000                      214    17.288680  9.899321e+11  1.299703e+12  1.660848e+12  1.222646e+12  1.524917e+12  2.045923e+12  2.208294e+12  2.292470e+12  2.059242e+12  1.363482e+12
Canada                 8      44877              44004    1082361          161133                   24.12      305   10431000000                      296    61.945430  1.319265e+12  1.468820e+12  1.552990e+12  1.374625e+12  1.617343e+12  1.793327e+12  1.828366e+12  1.846597e+12  1.805750e+12  1.556509e+12
Italy                  9      42635              40695     767280          171442                   18.00      227    6530000000                      109    33.667230  1.958564e+12  2.222524e+12  2.417508e+12  2.209484e+12  2.144936e+12  2.306974e+12  2.097929e+12  2.153226e+12  2.173256e+12  1.845428e+12
South Korea           10      42534              42174     761076          124789                   17.89      215   11007000000                      221     2.279353  1.095176e+12  1.220912e+12  1.091581e+12  9.830652e+11  1.192830e+12  1.307103e+12  1.335344e+12  1.434670e+12  1.556252e+12  1.539212e+12
Iran                  11      35889              35484     798505          211983                   22.25      218    9172000000                      119     5.707721  2.656022e+11  3.497366e+11  4.060709e+11  4.140591e+11  4.870696e+11  6.290823e+11  6.440193e+11  5.003998e+11  4.622848e+11  4.091917e+11
France                12      33407              32698     637552           99244                   19.08      235   10597000000                      166    17.020280  2.317862e+12  2.655817e+12  2.926803e+12  2.700076e+12  2.646230e+12  2.870409e+12  2.683007e+12  2.816078e+12  2.861236e+12  2.442483e+12
Spain                 13      32521              31781     726414          118758                   22.34      233    4923000000                      106    37.968590  1.261847e+12  1.476746e+12  1.636115e+12  1.496588e+12  1.427989e+12  1.487569e+12  1.330995e+12  1.362187e+12  1.380245e+12  1.206165e+12
Australia             14      31047              30232     760284           99637                   24.49      262    5386000000                      231    11.810810  7.497084e+11  8.566036e+11  1.058448e+12  9.317617e+11  1.152567e+12  1.402940e+12  1.552728e+12  1.583737e+12  1.474677e+12  1.356806e+12
Brazil                15      30840              30383     371926           84223                   12.06      167   12149000000                       59    69.648030  1.107627e+12  1.397114e+12  1.695855e+12  1.666996e+12  2.208838e+12  2.616157e+12  2.465228e+12  2.472819e+12  2.456044e+12  1.802212e+12

In [2]:
def answer_two():
    top15 = answer_one()
    avgGDP = top15[['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']].mean(axis=1)
    avgGDP = avgGDP.sort_values(ascending=False)
    return avgGDP

answer_two()

Country
United States         1.570403e+13
China                 7.048894e+12
Japan                 5.239642e+12
Germany               3.590126e+12
United Kingdom        2.791877e+12
France                2.692000e+12
Italy                 2.152983e+12
Brazil                1.988889e+12
Russian Federation    1.666746e+12
Canada                1.616359e+12
India                 1.602352e+12
Spain                 1.406644e+12
South Korea           1.275614e+12
Australia             1.211998e+12
Iran                  4.567516e+11
dtype: float64

In [3]:
def answer_three():
    top15 = answer_one()
    avgGDP = answer_two()
    sixth_ct = avgGDP.index[5]
    sixth_row = top15.loc[sixth_ct]
    diff = sixth_row['2015'] / sixth_row['2006']
    return float(diff)

answer_three()

1.0537658982423401

In [4]:
def answer_four():
    top15 = answer_one()
    top15['Self to Citation Ratio'] = top15['Self-citations'] / top15['Citations']
    max_country = top15['Self to Citation Ratio'].idxmax()
    max_value = float(top15['Self to Citation Ratio'].max())
    return(max_country, max_value)

answer_four()

('China', 0.6970630544852335)

In [5]:
def answer_five():
    top15 = answer_one()
    top15['Population'] = top15['Energy Supply'] / top15['Energy Supply per Capita']
    top15 = top15.sort_values('Population', ascending=False)
    country_name = top15.index[2]
    return country_name
answer_five()

'United States'

In [6]:
def answer_six():
    top15 = answer_one()
    top15['Population'] = top15['Energy Supply'] / top15['Energy Supply per Capita']
    top15['Citable docs per Capita'] = top15['Citable documents'] / top15['Population']
    corr = top15['Citable docs per Capita'].corr(top15['Energy Supply per Capita'])
    return float(corr)
answer_six()

0.6905473831164103

In [7]:
def answer_seven():
    top15 = answer_one()
    ContinentDict  = {'China':'Asia', 
                      'United States':'North America', 
                      'Japan':'Asia', 
                      'United Kingdom':'Europe', 
                      'Russian Federation':'Europe', 
                      'Canada':'North America', 
                      'Germany':'Europe', 
                      'India':'Asia',
                      'France':'Europe', 
                      'South Korea':'Asia', 
                      'Italy':'Europe', 
                      'Spain':'Europe', 
                      'Iran':'Asia',
                      'Australia':'Australia', 
                      'Brazil':'South America'}
    top15['Population'] = top15['Energy Supply'] / top15['Energy Supply per Capita']
    result = top15['Population'].groupby(ContinentDict).agg(['size', 'sum', 'mean', 'std'])
    result.index.name = 'Continent'
    return result

answer_seven()

               size               sum              mean           std
Continent
Asia              5   2898666386.6106   579733277.32212  6.790979e+08
Australia         1   23316017.316017   23316017.316017           NaN
Europe            6  457929667.216372   76321611.202729  3.464767e+07
North America     2   352855249.48025  176427624.740125  1.996696e+08
South America     1  205915254.237288  205915254.237288           NaN